env: develop
host: http://backend-1:8080
server:
  defaultPort: 8080
  port: 8080
  corsOrigins: "http://localhost:5173,http://localhost:8080,https://localhost:3443"
redis:
  host: redis
  port: 6379
  password: ""
  key: "my-cryptochain"
