// Code generated by MockGen. DO NOT EDIT.
// Source: ./web/domain/repository/block_chain.go

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	time "github.com/watariRyo/cryptochain-go/internal/time"
	model "github.com/watariRyo/cryptochain-go/web/domain/model"
)

// MockBlockChainInterface is a mock of BlockChainInterface interface.
type MockBlockChainInterface struct {
	ctrl     *gomock.Controller
	recorder *MockBlockChainInterfaceMockRecorder
}

// MockBlockChainInterfaceMockRecorder is the mock recorder for MockBlockChainInterface.
type MockBlockChainInterfaceMockRecorder struct {
	mock *MockBlockChainInterface
}

// NewMockBlockChainInterface creates a new mock instance.
func NewMockBlockChainInterface(ctrl *gomock.Controller) *MockBlockChainInterface {
	mock := &MockBlockChainInterface{ctrl: ctrl}
	mock.recorder = &MockBlockChainInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBlockChainInterface) EXPECT() *MockBlockChainInterfaceMockRecorder {
	return m.recorder
}

// AddBlock mocks base method.
func (m *MockBlockChainInterface) AddBlock(data string, tm time.TimeProvider) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddBlock", data, tm)
}

// AddBlock indicates an expected call of AddBlock.
func (mr *MockBlockChainInterfaceMockRecorder) AddBlock(data, tm interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddBlock", reflect.TypeOf((*MockBlockChainInterface)(nil).AddBlock), data, tm)
}

// GetBlock mocks base method.
func (m *MockBlockChainInterface) GetBlock() []*model.Block {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlock")
	ret0, _ := ret[0].([]*model.Block)
	return ret0
}

// GetBlock indicates an expected call of GetBlock.
func (mr *MockBlockChainInterfaceMockRecorder) GetBlock() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlock", reflect.TypeOf((*MockBlockChainInterface)(nil).GetBlock))
}

// IsValidChain mocks base method.
func (m *MockBlockChainInterface) IsValidChain() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsValidChain")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsValidChain indicates an expected call of IsValidChain.
func (mr *MockBlockChainInterfaceMockRecorder) IsValidChain() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsValidChain", reflect.TypeOf((*MockBlockChainInterface)(nil).IsValidChain))
}

// ReplaceChain mocks base method.
func (m *MockBlockChainInterface) ReplaceChain(ctx context.Context, chain []*model.Block, tm time.TimeProvider, validTransactionDataFn func(context.Context, []*model.Block, []*model.Block) bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ReplaceChain", ctx, chain, tm, validTransactionDataFn)
}

// ReplaceChain indicates an expected call of ReplaceChain.
func (mr *MockBlockChainInterfaceMockRecorder) ReplaceChain(ctx, chain, tm, validTransactionDataFn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceChain", reflect.TypeOf((*MockBlockChainInterface)(nil).ReplaceChain), ctx, chain, tm, validTransactionDataFn)
}

// UnmarshalAndReplaceBlock mocks base method.
func (m *MockBlockChainInterface) UnmarshalAndReplaceBlock(ctx context.Context, payload []byte, tm time.TimeProvider, fn func([]*model.Block) error, validTransactionDataFn func(context.Context, []*model.Block, []*model.Block) bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UnmarshalAndReplaceBlock", ctx, payload, tm, fn, validTransactionDataFn)
}

// UnmarshalAndReplaceBlock indicates an expected call of UnmarshalAndReplaceBlock.
func (mr *MockBlockChainInterfaceMockRecorder) UnmarshalAndReplaceBlock(ctx, payload, tm, fn, validTransactionDataFn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnmarshalAndReplaceBlock", reflect.TypeOf((*MockBlockChainInterface)(nil).UnmarshalAndReplaceBlock), ctx, payload, tm, fn, validTransactionDataFn)
}
